project:
  type: website

website:
  title: "Hector's Blog"
  navbar:
    left: 
      - text: Research
        href: research_projects.qmd
      - text: Sci-Comm
        href: science_communication.qmd
      - text: Resume
        href: resume.qmd
      - text: CV
        href: cv.qmd
    right:
      - text: about
        href: about.qmd
      - icon: twitter
        href: https://twitter.com/hfajardo9
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

